### ISSUE TITLE
Allow soundboard audio to be sent to specific audio channels

### ISSUE THREAD

**Issue by johnz1** [nickdanger3d/simplesoundboard#25]
I'd like to send soundboard audio to the surround speakers, leaving the music and PS2 audio to the front speakers.

If this is any kind of significant amount of work, don't bother - it's not important

**Comment by nickdanger3d** [comment]
can't do it in pygame. However, fool around with voicemeeter banana http://vb-audio.pagesperso-orange.fr/Voicemeeter/banana.htm that might be able to do it
